project:
  type: website

website:
  title: "Exploratory Data Analysis (EDA) Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/babakfifoo
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



